### ISSUE TITLE
Cannot delete account

### ISSUE THREAD

**Issue by daniel-karl** [plausible-insights/plausible#48]
Hi there,

I am experiencing the following behavior:

1. created an account
2. added a website, added your script to my website
4. tested website, noticed you *do* use cookies despite advertising you don't, so felt tricked
5. clicked delete account, got message "account cannot be deleted", 
6. account still there, but website disappeared in plausible account
7. cannot recreate website because it seems it wasn't actually deleted
8. ...and cannot delete account either.

Thanks,
Daniel

**Comment by daniel-karl** [comment]
Hi, can you please manually remove my account, so I can recreate it, to try whether the cookie was in fact my own login cookie?

**Comment by ukutaht** [comment]
Hey, sorry for the issues. I've reset everything for `covid19map.io` so you can try again.

**Comment by daniel-karl** [comment]
thanks works
