### ISSUE TITLE
False advertising? In fact not cookies-free?!

### ISSUE THREAD

**Issue by daniel-karl** [plausible-insights/plausible#49]
Hi,

you advertise this product as being cookie-free.
I like that, so I added plausible to my website.

However, when I checked there were plausible cookies in my browser.

Thanks,
Daniel

**Comment by daniel-karl** [comment]
![Screen Shot 2020-03-29 at 1 21 47 PM](https://user-images.githubusercontent.com/55108245/77855733-4eec7400-71c0-11ea-816e-4a24acf01218.png)

**Comment by daniel-karl** [comment]
> [...] It doesn't use cookies and [...]

**Comment by ukutaht** [comment]
Hey Daniel,

Plausible does not use cookies for analytics by default. However, we still set a cookie to store your login state on the actual plausible.io website. This does not impact your website visitors.

Can you share a screenshot of the cookie you mentioned?

**Comment by daniel-karl** [comment]
I cannot, because I cannot recreate my site. After having tried to delete my account it removed my website, however, I still cannot recreate the website.

**Comment by daniel-karl** [comment]
I would like to retry, but I cannot recreate the website - it's not in my account, but creating also fails stating it's already in my account.

**Comment by daniel-karl** [comment]
i can confirm no cookies
