### ISSUE TITLE
plausible.js includes a lot of unnecessary padding

### ISSUE THREAD

**Issue by chris-morgan** [plausible-insights/plausible#52]
The first 962 bytes of https://plausible.io/js/plausible.js (as it is at present) is unnecessary build tool nonsense and should be deleted. Combined with the matching three bytes at the end, this makes up about 30% of the file size (26% gzipped).

The whole inner thing is an IIFE doing no exports, so it doesn’t need that wrapping at all.

Skimming through it, there’s quite a lot of other low-hanging fruit too. Some examples: the programmatic RegExp construction in IIFE for cookie matching can readily be reduced to `/(?:^|; )plausible_user=([^;]*)/`; `XMLHttpRequest.DONE` can become `4`; `window.foo` (`i.foo` as minified) is a waste of `window.`, just write `foo` if you know it exists; more IIFEs can be vanquished.

I’m also bemused by the `plausible_user` encoding—to encode it, you URL-encode values, then in putting them in an object JSON-encode them. When decoding it, you URL-decode the entire result first, so that you’re URL-decoding twice. That seems wrong, though probably fairly harmless in practice. But it’d be more compact if you just encoded the object directly and then URL-encoded it once.

Also just FYI, no browser will respect your request for a cookie expiry 3000 years in the future! (I’m guessing you’ve used someone else’s code there; for something like this I’d say hand-write the entire lot, inlining any dependencies manually and making sure they’re sanely written.)

Then as often happens I got sucked into manual minification which is a hobby of mine. Here’s what I ended up with:

```javascript
!function(e){"use strict";try{var t=window.plausible&&plausible.q||[],n=0,i=function(){return(location.search.match(/[?&](?:ref|source|utm_source)=([^?&]+)/)||[null])[0]},r=plausible=function(t,n){if(/localhost$/.test(location.hostname)||"file:"==location.protocol)return console.warn("[Plausible] Ignoring event because website is running locally");if("prerender"==document.visibilityState)return console.warn("[Plausible] Ignoring event because document is prerendering");var r={name:t,url:location.protocol+"//"+location.hostname+location.pathname+location.search,domain:s,referrer:document.referrer||null,source:i(),user_agent:navigator.userAgent,screen_width:innerWidth};c&&((t=(t=document.cookie.match(/(?:^|; )plausible_user=([^;]*)/))?JSON.parse(decodeURIComponent(t[1])):null)?(r.initial_referrer=t.initial_referrer&&decodeURIComponent(t.initial_referrer),r.initial_source=t.initial_source&&decodeURIComponent(t.initial_source)):((t=new Date).setTime(t.getTime()+94608e6),document.cookie="plausible_user="+JSON.stringify({initial_referrer:(r.initial_referrer=document.referrer||null)&&encodeURIComponent(r.initial_referrer),initial_source:(r.initial_source=i())&&encodeURIComponent(r.initial_source)})+"; expires="+t.toUTCString()+"; samesite=strict; path=/"));(t=new XMLHttpRequest).open("POST",e+"/api/event"),t.setRequestHeader("content-type","text/plain"),t.send(JSON.stringify(r)),t.onreadystatechange=function(){4==t.readyState&&n&&n.callback&&n.callback()}},o=function(){r("pageview")},a=document.querySelector('[src*="'+e+'"]'),s=a&&a.getAttribute("data-domain")||location.hostname,c="string"==typeof(a&&a.getAttribute("data-track-acquisition")),l=history.pushState;for(l&&(history.pushState=function(){l.apply(this,arguments),o()},addEventListener("popstate",o));n<t.length;n++)r.apply(this,t[n]);o()}catch(r){(new Image).src=e+"/api/error?message="+encodeURIComponent(r.message)}}("https://plausible.io");
```

1.88KB, 0.92KB gzipped (40%/36% smaller compared to the current baseline). Even less warranty on that than any warranty that might have been offered, but it *should* behave the same. Do what you will with it, including ignoring it if you like.

Just passing by, I have no intention of using your product at this time and do not plan to speak further about this beyond what I have already written in this issue.

**Comment by mgan59** [comment]
> Also just FYI, no browser will respect your request for a cookie expiry 3000 years in the future! (I’m guessing you’ve used someone else’s code there; for something like this I’d say hand-write the entire lot, inlining any dependencies manually and making sure they’re sanely written.)

Thought this wasn't supposed to use/set cookies as described on [this article](https://plausible.io/blog/remove-google-analytics)

**Comment by ukutaht** [comment]
@chris-morgan Thanks for the thorough review of the script :) I'll definitely use you insights to imrove it going forward.

@mgan59 We don't use cookies for tracking by default, but there's an option to enable a cookie for conversion attribution. Our [data policy](https://plausible.io/data-policy#first-thing-first-what-we-collect-and-what-we-use-it-for) explains this in more detail
