### ISSUE TITLE
See users flow inside the Website

### ISSUE THREAD

**Issue by migueltorrescosta** [plausible-insights/plausible#59]
One of the main reasons for me to want Analytics is to see the users flow inside the Website itself, so that I can tailor it to the way the users are actually using it. The way I did it previously (when I had Google Analytics) was to have a Sankey Diagram which showed me how many users were flowing from one page to another. Is this something supported by Plausible or planned to be supported at some point?

**Details:**
For this to be useful for larger websites, I will describe how I would imagine it for a Blog (The web's standard Hello World of websites :P )

The user would define custom page types. In this case, it would be:
_HomePage:_ Has it's own type
_About:_ Has it's own type
_Posts:_ All posts share this type.

Then the Analytics allows me to select a page type (Say HomePage) and see how users flow from there (maybe 90% go to a Posts type page, and 10% to the About page).

Does this make sense?

**Example Diagram:**
![image](https://user-images.githubusercontent.com/6451658/80864430-d8410b80-8c82-11ea-9735-1af6682a5dd5.png)

**Comment by ukutaht** [comment]
Hey, thanks for the feature request. It makes sense but it's a very advanced feature and I think it will take a long time to implement it.

We collect feature requests over at plausible.nolt.io where people can vote on them and I keep an open roadmap. I've copied your request over there so everything is in one place: https://plausible.nolt.io/109

Let's continue the discussion over the and I'll close this for now :)

**Comment by migueltorrescosta** [comment]
Thank you for the prompt reply!
