### ISSUE TITLE
Cloudflare - feedback.plausible.io issue

### ISSUE THREAD

**Issue by kingthorin** [plausible-insights/plausible#60]
Was reading: https://opensource.com/article/20/5/plausible-analytics , couldn't get to your roadmap.

https://feedback.plausible.io/roadmap
> Error 525 Ray ID: 58d599a59b4fc5ec • 2020-05-02 23:42:41 UTC
> SSL handshake failed
> You Browser Working Newark
> Cloudflare Working
> feedback.plausible.io
> Host Error
> What happened?
> Cloudflare is unable to establish an SSL connection to the origin server.

![Screenshot_20200502-195228](https://user-images.githubusercontent.com/7570458/80895031-82825880-8cae-11ea-9eaf-532626b3f8a8.png)

**Comment by ukutaht** [comment]
Hey, thanks for letting me know of the issue.

We moved away from the custom domain and now the feedback board is on plausible.nolt.io

I've set up a redirect from feedback.plausible.io -> plausible.nolt.io. Big thanks for bringing this to my attention!
